## Codebook For run_analysis.R
### Getting And Cleaning Data Course Project | Coursera

### By Dwayne Macadangdang

Data for this project was collected from the following study: Human Activity Recognition Using Smartphones Data Set 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

### Experimental Design and Background
From the website: "The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data."

### Raw Data
The accelerometer inertial signal data are stored in files by training and test sets, then by x and y axis. The original feature names (columns) are contained in the file "features.txt" in this repository. The six activity labels are available in the file "activity_labels.txt", also in this repository.

### Processed Data
Steps: downloaded data, read from all test and training files as well as the activity and feature files as dataframes, combined test and training data into a dataframe, reduced data to only the desired columns (subject, activity, columns containing mean or stand deviation) and converted to a datatable, replaced numeric activity values with descriptions, edited column names for readability, arranged/grouped/summarized the data, wrote data to output file.

The final variable (column) names used in this project are saved in the repository file "final_column_names.txt".

The data can be verified to be "tidy" by viewing the file "Tidy.xlsx" in the repository.
* Each variable name is unique (using Highlight Cell Rules > Duplicate Values...)
* Each observation is saved in its own row (30 subjects, 6 activities each = 180 rows)
* The file stores one kind of observation.

