# Coursera.Getting_Cleaning_Data.Course_Project
## Repository for Getting and Cleaning Data Course Project - Dwayne Macadangdang

This is the course project for the class Getting and Cleaning Datak offered  by Coursera.

## Repository Contents
The repository contains the following files:
* This README markdown file.
* activity_labels.txt - activity labels
* Codebook.Rmd - required file describes the contents, structure, and layout of the data collection, and records the process.
* features.txt - contains all original column names
* final_column_names.txt - contains list of columns used
* run_analysis.R - required script to process the data
* Tidy.txt - required output file in .csv format
* Tidy.xlsx - Excel import of Tidy.txt to verify that the data is tidy

## Script
* Sets working directory, load library dependencies 
* Reads the activity and feature data from files
* Reads the training and test data from files
* Combines training and test data
* Creates preliminary columns
* Combines all data
* Reduces data to only the columns that contain subject, activity, mean and standard deviation metrics
* Converts numeric activity values to descriptions
* Cleans up column names for readability
* Arrange, group and summarize (mean) data table using dplyr verbs
* Write data to text file output